import fs from 'node:fs';
import {fileURLToPath} from 'node:url';
import path from 'node:path';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const read=f=>fs.readFileSync(path.join(root,f),'utf8');
const copy=JSON.parse(read('src/data/examples.json')),caseData=JSON.parse(read('src/data/case.json'));
const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const icon=id=>`<svg class="icon" viewBox="0 0 24 24" aria-hidden="true"><use href="#i-${id}"/></svg>`;
function table(columns,rows){return `<table><thead><tr>${columns.map(x=>`<th scope="col">${esc(x)}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr>${row.map((x,i)=>`<td data-label="${esc(columns[i])}"><span data-value>${esc(x)}</span></td>`).join('')}</tr>`).join('')}</tbody></table>`;}
function data(value){
 if(value.columns)return table(value.columns,value.rows);
 if(value.tables)return `<div class="source-stack">${value.tables.map(x=>`<div>${icon('table')}<span data-value>${esc(x)}</span></div>`).join('')}</div><p class="data-meta" data-value>${esc(value.period)}</p>`;
 if(value.folder)return `<div class="folder-data">${icon('folder')}<strong data-value>${esc(value.folder)}</strong><span data-value>${esc(value.file)}</span></div>`;
 if(value.lines)return `<div class="paper-data"><strong>${icon('file')}${esc(value.file)}</strong>${value.lines.map(x=>`<p data-value>${esc(x)}</p>`).join('')}</div>`;
 if(value.text)return `<div class="message-data">${value.title?`<strong data-value>${esc(value.title)}</strong>`:''}<p data-value>${esc(value.text)}</p>${value.variants?`<ul class="variants">${value.variants.map(x=>`<li><strong>${esc(x.channel)}</strong><span data-value>${esc(x.format)}</span></li>`).join('')}</ul>`:''}</div>`;
 if(value.title)return `<div class="event-data"><strong data-value>${esc(value.title)}</strong>${Object.entries(value).filter(([key])=>key!=='title').map(([,v])=>`<p data-value>${esc(v)}</p>`).join('')}</div>`;
 return `<dl class="data-list">${Object.entries(value).map(([key,v])=>`<div><dt>${esc(key)}</dt><dd>${Array.isArray(v)?`<ul>${v.map(x=>`<li data-value>${esc(x)}</li>`).join('')}</ul>`:`<span data-value>${esc(v)}</span>`}</dd></div>`).join('')}</dl>`;
}
const tabIcons={leads:'message',status:'process',documents:'file',reports:'table',content:'image',publishing:'image',crm:'table',email:'message',meetings:'process',files:'folder'};
const tabs=(list,kind)=>`<div class="scenario-selectors ${kind}-selectors" aria-label="${kind==='hero'?'Примеры автоматизации':'Примеры задач'}">${list.map((s,i)=>`<button type="button" data-select="${i}" aria-pressed="${i===0}" aria-controls="${kind}-sample-${i}">${kind==='tasks'?icon(tabIcons[s.id]):''}<span>${esc(s.tab)}</span></button>`).join('')}</div>`;
const controls=(kind)=>`<div class="demo-controls">${kind==='tasks'?'<div class="cycle-progress" aria-hidden="true"><i></i></div><button class="replay-button" type="button" data-replay>Повторить пример ↻</button>':''}<button class="demo-stop" type="button" data-pause aria-label="${copy.controls.pause}" aria-pressed="false">Остановить</button><span class="sr-only demo-announcement" role="status"></span></div>`;
const arrow='<div class="demo-route" aria-hidden="true"><span>→</span><i class="route-signal"></i></div>';
function heroSample(s,i){const result=s.resultData|| (s.rows?{columns:s.columns,rows:s.rows}:{file:s.documentTitle,lines:s.documentLines});return `<article class="scenario hero-scenario" id="hero-sample-${i}" ${i?'hidden inert aria-hidden="true"':''}><div class="source-card sample-card"><p class="data-label">${copy.hero.taskLabel}</p><h3>${esc(s.task)}</h3><div class="data-body">${data(s.source)}</div></div>${arrow}<div class="result-card sample-card"><p class="data-label">${copy.hero.resultLabel}</p><h3>${esc(s.result)}</h3><div class="data-body">${data(result)}</div><p class="result-footer">${icon('check')}<span>${esc(s.footer)}</span></p></div></article>`;}
function taskSample(s,i){return `<article class="scenario task-scenario" id="tasks-sample-${i}" ${i?'hidden inert aria-hidden="true"':''}><div class="task-explanation"><h3>${esc(s.title)}</h3><p>${esc(s.description)}</p>${s.note?`<p class="scenario-note">${esc(s.note)}</p>`:''}</div><div class="task-visual"><div class="source-card sample-card"><p class="data-label">${esc(s.sourceLabel)}</p><div class="data-body">${data(s.source)}</div></div>${arrow}<div class="result-card sample-card"><p class="data-label">${esc(s.resultLabel)}</p><div class="data-body">${data(s.result)}</div><p class="result-footer">${icon('check')}<span>${esc(s.footer)}</span></p></div></div></article>`;}
const hero=`<section class="hero container" id="hero" aria-labelledby="hero-title"><div class="neural-stage" aria-hidden="true"><div class="neural-fallback"></div><canvas id="neural-canvas"></canvas><div class="neural-scrim"></div></div><div class="hero-copy"><h1 id="hero-title"><span>Меньше рутины.</span><span>Больше времени</span><span class="hero-last">на бизнес.</span></h1><p class="lead">Помогаю автоматизировать повторяющиеся задачи с помощью AI и ваших рабочих сервисов.</p><div class="hero-actions"><a class="button button-primary" href="#contact">Обсудить автоматизацию ${icon('arrow')}</a><a class="button button-ghost" href="#project">Посмотреть проект ↓</a></div><p class="hero-note muted">Не знаете, с чего начать? Посмотрим вместе.</p></div><div class="hero-demo" data-carousel="hero"><p class="eyebrow">${copy.hero.label}</p><div class="scenario-stack">${copy.hero.scenarios.map(heroSample).join('')}</div>${tabs(copy.hero.scenarios,'hero')}${controls('hero',6)}<p class="demo-caption">${copy.hero.caption}</p></div><a class="hero-bottom" href="#tasks" aria-label="Задачи для автоматизации">↓</a></section>`;
const tasks=`<section class="section container tasks-section" id="tasks" aria-labelledby="tasks-title"><div class="section-heading"><p class="eyebrow">${copy.tasks.eyebrow}</p><h2 id="tasks-title">${copy.tasks.heading}</h2><p class="lead">${copy.tasks.intro}</p></div><div class="tasks-workspace" data-carousel="tasks">${tabs(copy.tasks.scenarios,'tasks')}<div class="scenario-stack">${copy.tasks.scenarios.map(taskSample).join('')}</div>${controls('tasks',10)}</div><p class="section-note muted">${copy.tasks.caption}</p></section>`;
const german=read('src/data/case-listing-de.txt').trim();
const source=`<div class="case-source sample-card"><h3><span class="service-badge telegram-badge"><svg viewBox="0 0 24 24" aria-hidden="true"><path fill="currentColor" d="m21 3-4 18-6-5-3 3 1-6 9-7-11 6-5-2Z"/></svg></span>Telegram</h3><p class="muted">${esc(caseData.telegram.label)}</p><div class="case-device"><strong>${esc(caseData.model)}</strong>${caseData.telegram.lines.slice(1).map(x=>`<p>${esc(x)}</p>`).join('')}</div><p class="photo-unavailable">Оригинальные фотографии HP не предоставлены.</p></div>`;
const listing=`<div class="case-listing sample-card"><h3><span class="service-badge">${icon('file')}</span>Материалы объявления</h3><p class="muted">Текст на немецком и папка с материалами</p><div class="case-listing-excerpt" lang="de"><strong>${caseData.model}</strong><p>${caseData.processor} · ${caseData.ram} RAM · ${caseData.storage} · 14-Zoll-Display</p><p>${esc(german.split("\n\n")[2])}</p><p>${esc(german.split("\n\n")[4])}</p><p class="article-number">Artikelnummer: ${caseData.articleNumber}</p></div><p class="file-label">${icon('folder')}${caseData.materials.displayFileName}</p></div>`;
const sheet=`<div class="case-sheet sample-card"><h3><span class="service-badge">${icon('table')}</span>Google Sheets</h3><p class="muted">Данные ноутбука</p><div class="case-sheet-identity"><strong>${caseData.model}</strong><span>${caseData.processor}</span></div>${table([caseData.sheet.columns[0],caseData.sheet.columns[3],caseData.sheet.columns[4]],[[caseData.articleNumber,caseData.ram,caseData.sheet.row[4]]])}</div>`;
const project=`<section class="section container project-section" id="project" aria-labelledby="project-title"><div class="case-main-row"><div class="case-copy"><p class="eyebrow">РЕАЛИЗОВАННЫЙ ПРОЕКТ</p><h2 id="project-title">Из характеристик и фото — в объявление на немецком.</h2><p class="lead">Telegram-помощник для продавца ноутбуков в Германии.</p><p class="case-accent">Объявление, данные и материалы — в одном процессе.</p><div class="case-fact">${icon('file')}<div><h3>Задача</h3><p>Подготовка объявлений на немецком и сохранение данных и фотографий ноутбуков.</p></div></div><div class="case-fact">${icon('settings')}<div><h3>Решение</h3><p>Помощник получает характеристики и фото в Telegram, создаёт объявление, сохраняет данные в Google Sheets и формирует папку с материалами.</p></div></div><a class="button button-primary" href="#contact">Обсудить автоматизацию ${icon('arrow')}</a></div><div class="case-showcase"><div class="case-scene">${source}<svg class="case-branches" aria-hidden="true"><path/><path/></svg><div class="case-outputs">${listing}${sheet}</div><div class="flight-layer" aria-hidden="true"></div></div><p class="muted case-caption">${caseData.publicCaption}</p></div></div><details class="case-details" id="case-details"><summary aria-controls="case-detail-body" aria-expanded="false">Материалы кейса</summary><div id="case-detail-body" class="case-detail-grid"><section class="detail-input" aria-label="Telegram"><h3>Telegram</h3><p>${caseData.telegram.lines.map(esc).join('<br>')}</p></section><section class="detail-document" aria-label="Текст объявления"><h3>${caseData.materials.displayFileName}</h3><div lang="de" class="german-full">${german.split('\n\n').map(x=>`<p>${esc(x).replaceAll('\n','<br>')}</p>`).join('')}</div></section><section class="detail-output" aria-label="Таблица и файлы"><h3>Google Sheets</h3><div class="detail-table">${table(caseData.sheet.columns,[caseData.sheet.row])}</div><h3>Файлы</h3><p>${caseData.materials.displayFileName}</p><p>Оригинальные фотографии HP не предоставлены.</p></section></div></details></section>`;
const stages=[['Разбор процесса','Выясняю, какие действия повторяются, где находятся данные и что можно автоматизировать.','file'],['Разработка и внедрение','Разрабатываю решение для выбранной задачи, подключаю нужные сервисы и проверяю работу.','settings'],['Сопровождение','После внедрения можно продолжить работу в формате ежемесячного сопровождения.','shield']];
const finale=`<section class="final-section container" aria-label="Как работаю и контакт"><div class="final-panel"><div id="process" aria-labelledby="process-title"><p class="eyebrow">КАК РАБОТАЮ</p><h2 id="process-title">Сначала разбираю процесс. Затем внедряю решение.</h2><div class="stages">${stages.map(([title,desc,ico],i)=>`<article class="stage"><span class="stage-number">0${i+1}</span><div class="stage-heading">${icon(ico)}<h3>${title}</h3></div><p>${desc}</p></article>`).join('')}</div><div class="work-outcome">${icon('check')}<p>После разбора вы понимаете, какие задачи можно автоматизировать и с какой стоит начать.</p><p class="work-conditions">Объём работ, стоимость и условия обсуждаем для конкретной задачи.</p></div></div><div id="contact" aria-labelledby="contact-title">${read('scripts/contact.html')}</div><footer class="site-footer"><a class="brand" href="#hero">TIGRAN <span>AI</span></a><a href="https://t.me/tigran_ai">@tigran_ai</a></footer></div></section>`;
let shell=read('scripts/shell.html').replace('</defs>','<symbol id="i-shield" viewBox="0 0 24 24"><path d="M12 2 3 6v5c0 5 4 9 9 11 5-2 9-6 9-11V6Z"/><path d="m7 12 3 3 7-7"/></symbol></defs>');
fs.writeFileSync(path.join(root,'index.html'),shell+'<main>'+hero+tasks+project+finale+'</main><script type="module" src="/src/main.js"></script></body></html>');

