import {gsap} from 'gsap';
export function createDemoMotion(reduced){
 const sessions=new Map();let selected=0;const panels=[...document.querySelectorAll('.work-panel')];
 function cancel(key){const s=sessions.get(key);if(!s)return;s.timeline.kill();s.tweens.forEach(t=>t.kill());s.nodes.forEach(n=>n.remove());s.host.classList.remove('playing');if(key==='case')gsap.set(s.host.querySelectorAll('.case-source,.case-outputs>.glass'),{clearProps:'transform,opacity,borderColor'});s.host.querySelectorAll('[style]').forEach(e=>{if(e.dataset.from!==undefined||e.dataset.to!==undefined||e.classList.contains('document-paper'))gsap.set(e,{clearProps:'transform,opacity'});});const status=s.host.querySelector('.demo-state');if(status)status.textContent='Результат';sessions.delete(key);}
 function cancelAll(){[...sessions.keys()].forEach(cancel);}
 function accent(s,el){if(!el)return;const base=s.host.getBoundingClientRect(),r=el.getBoundingClientRect(),overlay=document.createElement('div');overlay.className='demo-accent';Object.assign(overlay.style,{left:`${r.left-base.left-3}px`,top:`${r.top-base.top-3}px`,width:`${r.width+6}px`,height:`${r.height+6}px`});s.host.querySelector('.flight-layer')?.append(overlay);s.nodes.add(overlay);s.tweens.push(gsap.fromTo(overlay,{opacity:0},{opacity:.8,duration:.25,repeat:1,yoyo:true,onComplete:()=>{overlay.remove();s.nodes.delete(overlay);}}));}
 function transfer(s,source,target,label,duration=.8){if(!source||!target)return;const base=s.host.getBoundingClientRect(),a=source.getBoundingClientRect(),b=target.getBoundingClientRect(),node=document.createElement('span');node.className='data-flight';node.textContent=label;s.host.querySelector('.flight-layer').append(node);s.nodes.add(node);const x0=a.left-base.left+a.width/2,y0=a.top-base.top+a.height/2,x1=b.left-base.left+b.width/2,y1=b.top-base.top+b.height/2;gsap.set(node,{xPercent:-50,yPercent:-50});const x=gsap.quickSetter(node,'x','px'),y=gsap.quickSetter(node,'y','px'),opacity=gsap.quickSetter(node,'opacity'),progress={t:0};x(x0);y(y0);s.tweens.push(gsap.to(progress,{t:1,duration,ease:'power2.inOut',onUpdate:()=>{const t=progress.t;x(x0+(x1-x0)*t);y(y0+(y1-y0)*t-Math.sin(Math.PI*t)*18);opacity(Math.sin(Math.PI*t));},onComplete:()=>{node.remove();s.nodes.delete(node);accent(s,target);}}));}
 function run(key){if(key!=='work'&&key!=='case'){['lead','status','document'].forEach(cancel);}cancel(key);const host=document.querySelector(`[data-demo="${key}"]`);if(reduced.matches){host.querySelector('.demo-state')?.replaceChildren('Результат');return;}const s={host,nodes:new Set(),tweens:[],timeline:gsap.timeline({paused:true,onComplete:()=>cancel(key)})};sessions.set(key,s);host.classList.add('playing');const status=host.querySelector('.demo-state');if(status)status.textContent='Обработка';const tl=s.timeline;
 const from=name=>host.querySelector(`[data-from="${name}"]`),to=name=>host.querySelector(`[data-to="${name}"]`);
 if(key==='lead'){tl.call(()=>{accent(s,from('name'));accent(s,from('topic'));},[],0).call(()=>transfer(s,from('name'),to('name'),'Алексей'),[],.6).call(()=>transfer(s,from('topic'),to('topic'),'Консультация'),[],1.65).call(()=>accent(s,host.querySelector('tbody')),[],2.7).to({}, {duration:3.5},0);}
 else if(key==='status'){tl.call(()=>accent(s,from('state')),[],0).call(()=>transfer(s,from('id'),to('id'),'№104'),[],.6).call(()=>transfer(s,from('state'),to('state'),'Готово → выполнена'),[],1.7).call(()=>accent(s,host.querySelector('.demo-result .message-bubble')),[],2.8).to({}, {duration:3.6},0);}
 else if(key==='document'){tl.call(()=>accent(s,host.querySelector('.data-fields')),[],0);['company','date','service'].forEach((name,i)=>tl.call(()=>transfer(s,from(name),to(name),from(name).textContent),[],.6+i*.9));tl.fromTo(host.querySelector('.document-paper'),{y:5},{y:0,duration:.7,ease:'power2.out'},3.4).to({}, {duration:4.3},0);}
 else if(key==='work'){const panel=panels[selected];if(selected===0){[...panel.querySelectorAll('.work-inputs>div')].forEach((el,i)=>tl.call(()=>accent(s,el),[],i*.4));[...panel.querySelectorAll('.work-map>div')].forEach((el,i)=>tl.call(()=>accent(s,el),[],1.6+i*.6));tl.to({}, {duration:3.8},0);}else if(selected===1){const nodes=[...panel.querySelectorAll('.service-path>div')];nodes.forEach((el,i)=>{tl.call(()=>accent(s,el),[],i*.85);if(i<nodes.length-1)tl.call(()=>transfer(s,el.querySelector('strong'),nodes[i+1].querySelector('strong'),'Алексей · Консультация',.65),[],i*.85+.3);});tl.call(()=>accent(s,panel.querySelector('.result-mark')),[],3.5).to({}, {duration:4.2},0);}else{const zones=panel.querySelectorAll('.support-path>div');tl.call(()=>accent(s,zones[0]),[],0).call(()=>accent(s,zones[1]),[],1.2).call(()=>accent(s,zones[0]),[],2.4).to({}, {duration:3.4},0);}}
 else if(key==='case'){const source=host.querySelector('.case-source');tl.to(source,{borderColor:'#9eb7ce70',duration:.6,yoyo:true,repeat:1},0).fromTo(host.querySelectorAll('.case-outputs>.glass'),{y:6,opacity:.86},{y:0,opacity:1,duration:.8,stagger:.15},.5).to({}, {duration:1.6},0);}
 tl.play();
 }
 function select(index){cancel('work');selected=index;panels.forEach((p,i)=>{p.hidden=i!==index;p.setAttribute('aria-hidden',String(i!==index));});document.querySelectorAll('[data-stage]').forEach(b=>b.setAttribute('aria-pressed',String(Number(b.dataset.stage)===index)));document.querySelector('#work-status').textContent='Примеры этапов';run('work');}
 const handlers=[];function bind(el,type,fn){el.addEventListener(type,fn);handlers.push(()=>el.removeEventListener(type,fn));}
 document.querySelectorAll('[data-play-task]').forEach(b=>bind(b,'click',()=>run(b.dataset.playTask)));document.querySelectorAll('[data-stage]').forEach(b=>bind(b,'click',()=>select(Number(b.dataset.stage))));bind(document.querySelector('#work-replay'),'click',()=>run('work'));
 let casePlayed=false;const observer=new IntersectionObserver(entries=>entries.forEach(e=>{const key=e.target.dataset.demo;if(!e.isIntersecting)cancel(key);else if(key==='case'&&!casePlayed&&!reduced.matches){casePlayed=true;run('case');}}),{threshold:.2});document.querySelectorAll('[data-demo]').forEach(el=>observer.observe(el));
 const resize=()=>cancelAll(),visibility=()=>{if(document.hidden)cancelAll();};window.addEventListener('resize',resize);document.addEventListener('visibilitychange',visibility);reduced.addEventListener('change',cancelAll);bind(document.querySelector('#business'),'focus',cancelAll);
 return{run,select,cancelAll,get active(){return[...sessions.keys()];},destroy(){cancelAll();observer.disconnect();handlers.forEach(fn=>fn());window.removeEventListener('resize',resize);document.removeEventListener('visibilitychange',visibility);reduced.removeEventListener('change',cancelAll);}};
}
